version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: sh scripts/launch.sh
    # command: ./bin/server
    environment:
      RAILS_ENV: production
    volumes:
      - .:/webapp
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
    ports:
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: