version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  aws-ecs: circleci/aws-ecs@1.1.0
  aws-cli: circleci/aws-cli@0.1.16

executors:
  container:
    working_directory: ~/webapp
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          TZ: Asia/Tokyo


jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: root
          MYSQL_DATABASE: myapp_test
    working_directory: ~/webapp
    steps:
      - checkout
      - restore_cache:
          name: bundle installの結果をリストア
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock"}}
            - v1-dependencies-
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle
      - run:
          name: context設定の環境変数
          command: |
            echo "${MYSQL_PASSWORD}"
            echo "${MYSQL_USER}"
            echo "${MYSQL_HOST}"
      - save_cache:
          name: bundle installの結果をキャッシュ
          paths: ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: データベースの起動を待機
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: データベースのセットアップ
          command: bundle exec rails db:schema:load
      - run:
          name: RSpecのテストを実行
          command: bundle exec rspec ./spec/commons/
  
  #イメージのビルドとECRへのプッシュ
  build-image-and-push:
    executor: container
    steps:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_REGION
          repo: dishare-rails
          dockerfile: ./Dockerfile.prd
          create-repo: true
          attach-workspace: true
          setup-remote-docker: true
          

  #マイグレーションを実行        
  db-migrate-on-task-run:
    executor: container
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - run:
          name: "db migrate"
          command: |
            aws ecs run-task --region $AWS_REGION \
              --cluster $ECS_ARN \
              --task-definition neptune-task \
              --overrides file://scripts/run_task_db_migrate.json
   
  #デプロイ
  service-update:
    executor: container
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - aws-ecs/update-service:
          family: 'neptune-task'
          cluster-name: '${ECS_ARN}'
          service-name: 'hello-service-3'
          container-image-name-updates: "container=rails-v15,tag=latest"

workflows:
  version: 2.1
  rails-test-and-deploy:
    jobs:
      - test

      #イメージのビルドとプッシュ
      - build-image-and-push:
          requires:
            - test
          # filters:
          #   branches:
          #     only: master
      
      # マイグレーションを実行
      - db-migrate-on-task-run:
          requires:
            - build-image-and-push
          # filters:
          #   branches:
          #     only: master

      - service-update:
          requires:
            - db-migrate-on-task-run
          # filters:
          #   branches:
          #     only: master

      

      # - aws-ecs/run-task:
      #     requires:
      #       - aws-ecr/build-and-push-image
      #     aws-access-key-id: AWS_ACCESS_KEY_ID
      #     aws-secret-access-key: AWS_SECRET_ACCESS_KEY         
          
      #     cluster: '${ECS_ARN}'
      #     task-definition: 'neptune-task:${CIRCLE_SHA1}'



